FROM node:24-alpine

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn

RUN yarn install

EXPOSE 3000

ENV NODE_ENV=development

CMD ["yarn", "workspace", "twenty-server", "dev"]
