FROM node:24-alpine

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn

RUN yarn install

EXPOSE 5173

ENV NODE_ENV=development

CMD ["yarn", "workspace", "twenty-front", "dev"]
